Repository paulofranklim/anybody-here-chat, pull requests merged in 2024-07, with the labels that each got.

#10 feat:Enable swagger ui
  pom.xml
Labels: documentation

#17 Feature/enable changelog
  CHANGELOG.md
  pom.xml
Labels: documentation

#19 feat: User and Contact tables DDL flyway scripts
  src/main/resources/db/migration/V1__create-tables.sql
Labels: enhancement

#20 Feature/contacts domain implementation
  src/main/java/com/anybodyherechat/Application.java
  src/main/java/com/anybodyherechat/controller/ContactController.java
  src/main/java/com/anybodyherechat/entity/ContactEntity.java
  src/main/java/com/anybodyherechat/entity/ContactPK.java
  src/main/java/com/anybodyherechat/exception/ApiExceptionHandler.java
  src/main/java/com/anybodyherechat/exception/ContactException.java
  src/main/java/com/anybodyherechat/model/ApiExceptionDTO.java
  src/main/java/com/anybodyherechat/model/ContactResponseDTO.java
  src/main/java/com/anybodyherechat/repository/ContactRepository.java
  src/main/java/com/anybodyherechat/service/ContactService.java
  src/main/java/com/anybodyherechat/utils/ResponseUtils.java
  src/main/resources/anybody-here-chat-specs.yaml
  src/test/java/com/anybodyherechat/TestAnybodyHereChatApplication.java
Labels: enhancement

#22 feat: Update creation tables flyway script
  src/main/resources/db/migration/V1__create-tables.sql
Labels: enhancement

#26 feat: Unit test and Jacoco plugin
  pom.xml
  src/main/java/com/anybodyherechat/controller/ContactController.java
  src/test/java/com/anybodyherechat/service/ContactServiceTest.java
Labels: test

#30 Feature/sign up controller
  pom.xml
  src/main/java/com/anybodyherechat/config/SecurityConfig.java
  src/main/java/com/anybodyherechat/controller/AuthenticationController.java
  src/main/java/com/anybodyherechat/entity/UserEntity.java
  src/main/java/com/anybodyherechat/exception/NewUserException.java
  src/main/java/com/anybodyherechat/repository/AuthenticationRepository.java
  src/main/java/com/anybodyherechat/service/AuthenticationService.java
  src/main/java/com/anybodyherechat/service/impl/AuthenticationServiceImpl.java
  src/main/resources/anybody-here-chat-specs.yaml
  src/test/java/com/anybodyherechat/controller/it/AuthenticationControllerIT.java
  src/test/java/com/anybodyherechat/controller/unit/AuthenticationControllerTest.java
Labels: enhancement

#33 feat: dockerfile and docker compose scripts
  Dockerfile
  docker-compose.yml
Labels: enhancement

#31 feat: integration test for contact domain and small changes
  pom.xml
  src/main/java/com/anybodyherechat/entity/ContactEntity.java
  src/test/java/com/anybodyherechat/AnybodyHereChatApplicationTests.java
  src/test/java/com/anybodyherechat/TestAnybodyHereChatApplication.java
  src/test/java/com/anybodyherechat/TestcontainersConfiguration.java
  src/test/java/com/anybodyherechat/controller/it/AuthenticationControllerIT.java
  src/test/java/com/anybodyherechat/controller/it/ContactControllerIT.java
  src/test/java/com/anybodyherechat/controller/unit/AuthenticationControllerTest.java
  src/test/java/com/anybodyherechat/service/ContactServiceTest.java
  src/test/resources/application-test.properties
Labels: test
